var annotated =
[
    [ "le_clk_Time_t", "structle__clk___time__t.html", "structle__clk___time__t" ],
    [ "le_dls_Link_t", "structle__dls___link__t.html", "structle__dls___link__t" ],
    [ "le_dls_List_t", "structle__dls___list__t.html", "structle__dls___list__t" ],
    [ "le_mem_PoolStats_t", "structle__mem___pool_stats__t.html", "structle__mem___pool_stats__t" ],
    [ "le_sls_Link_t", "structle__sls___link__t.html", "structle__sls___link__t" ],
    [ "le_sls_List_t", "structle__sls___list__t.html", "structle__sls___list__t" ],
    [ "pa_Gnss_Date_t", "structpa___gnss___date__t.html", "structpa___gnss___date__t" ],
    [ "pa_Gnss_Position_t", "structpa___gnss___position__t.html", "structpa___gnss___position__t" ],
    [ "pa_Gnss_Time_t", "structpa___gnss___time__t.html", "structpa___gnss___time__t" ],
    [ "pa_mcc_CallEventData_t", "structpa__mcc___call_event_data__t.html", "structpa__mcc___call_event_data__t" ],
    [ "pa_mdc_Authentication_t", "structpa__mdc___authentication__t.html", "structpa__mdc___authentication__t" ],
    [ "pa_mdc_PktStatistics_t", "structpa__mdc___pkt_statistics__t.html", "structpa__mdc___pkt_statistics__t" ],
    [ "pa_mdc_ProfileData_t", "structpa__mdc___profile_data__t.html", "structpa__mdc___profile_data__t" ],
    [ "pa_mdc_SessionStateData_t", "structpa__mdc___session_state_data__t.html", "structpa__mdc___session_state_data__t" ],
    [ "pa_mrc_MobileCode_t", "structpa__mrc___mobile_code__t.html", "structpa__mrc___mobile_code__t" ],
    [ "pa_mrc_PreferredNetwork_t", "structpa__mrc___preferred_network__t.html", "structpa__mrc___preferred_network__t" ],
    [ "pa_mrc_ScanInformation_t", "structpa__mrc___scan_information__t.html", "structpa__mrc___scan_information__t" ],
    [ "pa_sim_Event_t", "structpa__sim___event__t.html", "structpa__sim___event__t" ],
    [ "pa_sms_Message_t", "structpa__sms___message__t.html", "structpa__sms___message__t" ],
    [ "pa_sms_Pdu_t", "structpa__sms___pdu__t.html", "structpa__sms___pdu__t" ],
    [ "pa_sms_SmsDeliver_t", "structpa__sms___sms_deliver__t.html", "structpa__sms___sms_deliver__t" ],
    [ "pa_sms_SmsSubmit_t", "structpa__sms___sms_submit__t.html", "structpa__sms___sms_submit__t" ]
];