var c__a_p_is =
[
    [ "Basic Type and Constant Definitions", "c_basics.html", null ],
    [ "Command Line Arguments API", "c_args.html", null ],
    [ "Directory API", "c_dir.html", null ],
    [ "Doubly Linked List API", "c_doubly_linked_list.html", null ],
    [ "Dynamic Memory Allocation API", "c_memory.html", null ],
    [ "Event Loop API", "c_event_loop.html", null ],
    [ "File Locking API", "c_flock.html", null ],
    [ "HashMap API", "c_hashmap.html", null ],
    [ "Hex string API", "c_hex.html", null ],
    [ "Logging API", "c_logging.html", null ],
    [ "Low-Level Messaging API", "c_messaging.html", null ],
    [ "Mutex API", "c_mutex.html", null ],
    [ "Path API", "c_path.html", null ],
    [ "Path Iterator API", "c_path_iter.html", null ],
    [ "Print APIs", "c_print.html", null ],
    [ "Real-time Clock API", "c_clock.html", null ],
    [ "Safe References API", "c_safe_ref.html", null ],
    [ "Semaphore API", "c_semaphore.html", null ],
    [ "Signals API", "c_signals.html", null ],
    [ "Singly Linked List API", "c_singly_linked_list.html", null ],
    [ "Thread Control API", "c_threading.html", null ],
    [ "Timer API", "c_timer.html", null ],
    [ "Unit Testing API", "c_test.html", null ],
    [ "UTF-8 String Handling API", "c_utf8.html", null ]
];