var searchData=
[
  ['security',['Security',['../basic_security.html',1,'basicConcepts']]],
  ['sandboxes',['Sandboxes',['../basic_security_sandbox.html',1,'basicSecurity']]],
  ['smack',['Smack',['../basic_security_smack.html',1,'basicSecurity']]],
  ['system_20clock_20api',['System Clock API',['../c_clock.html',1,'c_APIs']]],
  ['safe_20references_20api',['Safe References API',['../c_safe_ref.html',1,'c_APIs']]],
  ['semaphore_20api',['Semaphore API',['../c_semaphore.html',1,'c_APIs']]],
  ['signals_20api',['Signals API',['../c_signals.html',1,'c_APIs']]],
  ['sim',['SIM',['../c_sim.html',1,'legatoServicesFoundation']]],
  ['singly_20linked_20list_20api',['Singly Linked List API',['../c_singly_linked_list.html',1,'c_APIs']]],
  ['sms',['SMS',['../c_sms.html',1,'legatoServicesFoundation']]],
  ['sample_20code_20for_20mobile_20originated_20sms_20message',['Sample code for Mobile Originated SMS message',['../c_sms_sample_m_o.html',1,'c_sms']]],
  ['sample_20code_20for_20mobile_20terminated_20sms_20message',['Sample code for Mobile Terminated SMS message',['../c_sms_sample_m_t.html',1,'c_sms']]],
  ['supervisor_20control_20api',['Supervisor Control API',['../c_sup_ctrl.html',1,'legatoServicesSupervisor']]],
  ['supervisor_20state_20api',['Supervisor State API',['../c_sup_state.html',1,'legatoServicesSupervisor']]],
  ['supervisor_20watchdog_20api',['Supervisor Watchdog API',['../c_sup_wdog.html',1,'legatoServicesSupervisor']]],
  ['software_20update',['Software Update',['../c_update.html',1,'legatoServicesFoundation']]],
  ['system_20definition_20_2esdef',['System Definition .sdef',['../def_files_sdef.html',1,'defFiles']]],
  ['software_20packages',['Software Packages',['../getstarted_legato_pkgs.html',1,'getstartedInstallSoftware']]],
  ['source_20packages',['Source Packages',['../getstarted_source_pkgs.html',1,'getstartedInstallLegato']]],
  ['setup_20target',['Setup Target',['../getstarted_target_main.html',1,'getstartedMain']]],
  ['setup_20target_20software',['Setup Target Software',['../getstarted_target_setup.html',1,'getstartedTargetMain']]],
  ['services_20apis',['Services APIs',['../legato_services.html',1,'index']]],
  ['supervisor',['Supervisor',['../legato_services_supervisor.html',1,'legatoServicesApplication']]],
  ['start_20app',['Start App',['../start_apps.html',1,'demoApps']]],
  ['setname',['setname',['../tools_host_setname.html',1,'toolsHost']]],
  ['settime',['settime',['../tools_host_settime.html',1,'toolsHost']]],
  ['settz',['settz',['../tools_host_settz.html',1,'toolsHost']]],
  ['simu',['simu',['../tools_host_simu.html',1,'toolsHost']]],
  ['startapp',['startapp',['../tools_host_startapp.html',1,'toolsHost']]],
  ['startlegato',['startlegato',['../tools_host_startlegato.html',1,'toolsHost']]],
  ['statapp',['statapp',['../tools_host_statapp.html',1,'toolsHost']]],
  ['stopapp',['stopapp',['../tools_host_stopapp.html',1,'toolsHost']]],
  ['stoplegato',['stoplegato',['../tools_host_stoplegato.html',1,'toolsHost']]],
  ['sdir',['sdir',['../tools_target_sdir.html',1,'toolsTarget']]],
  ['setnet',['setNet',['../tools_target_set_net.html',1,'toolsTarget']]]
];
