var searchData=
[
  ['syntax',['Syntax',['../apiFilesSyntax.html',1,'apiFiles']]],
  ['security',['Security',['../basicSecurity.html',1,'basicConcepts']]],
  ['sandboxes',['Sandboxes',['../basicSecuritySandbox.html',1,'basicSecurity']]],
  ['smack',['SMACK',['../basicSecuritySmack.html',1,'basicSecurity']]],
  ['sample_20code_20of_20audio_20playback_20and_20capture',['Sample code of audio playback and capture',['../c_audioCapturePlayback.html',1,'']]],
  ['sample_20code_20of_20dtmf_20playback_20and_20decoding',['Sample code of dtmf playback and decoding',['../c_audiodtmf.html',1,'']]],
  ['sample_20code_20of_20audio_20settings_20for_20a_20dialing_20call',['Sample code of audio settings for a dialing call',['../c_audioMcc.html',1,'']]],
  ['system_20clock_20api',['System Clock API',['../c_clock.html',1,'c_APIs']]],
  ['sample_20code_20of_20an_20ecall_20test_20session_20with_20a_20local_20voice_20prompt',['Sample code of an eCall test session with a local voice prompt',['../c_ecallWPromptSample.html',1,'']]],
  ['sample_20code_20an_20ecall_20test_20session_20with_20a_20voice_20call_20connection',['Sample code an eCall test session with a voice call connection',['../c_ecallWVoiceSample.html',1,'']]],
  ['sample_20code_20of_20modem_20call_20control',['Sample code of Modem Call control',['../c_mccTest.html',1,'']]],
  ['sample_20code_20for_20data_20profiles',['Sample code for Data Profiles',['../c_mdcDataProfiles.html',1,'c_mdc']]],
  ['sample_20code_20for_20network_20interface_20settings',['Sample code for network interface settings',['../c_mdcDataSessions.html',1,'c_mdc']]],
  ['sample_20code_20for_20data_20statistics',['Sample code for Data Statistics',['../c_mdcDataStatistics.html',1,'c_mdc']]],
  ['sample_20code_20for_20band_20capabilities',['Sample code for Band Capabilities',['../c_mrcBandCapabilities.html',1,'c_mrc']]],
  ['sample_20code_20for_20get_20current_20network_20information',['Sample code for Get Current Network Information',['../c_mrcGetCurrentNetwork.html',1,'c_mrc']]],
  ['sample_20code_20for_20location_20information',['Sample code for Location information',['../c_mrcLocationinformation.html',1,'c_mrc']]],
  ['sample_20code_20for_20neighboring_20cells_20information',['Sample code for Neighboring Cells Information',['../c_mrcNeighborCells.html',1,'c_mrc']]],
  ['sample_20code_20for_20network_20registration',['Sample code for Network Registration',['../c_mrcNetworkRegistration.html',1,'c_mrc']]],
  ['sample_20code_20for_20network_20scan',['Sample code for Network Scan',['../c_mrcNetworkScan.html',1,'c_mrc']]],
  ['sample_20code_20for_20signal_20quality',['Sample code for Signal Quality',['../c_mrcQuality.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20configuration_20preferences',['Sample code for Radio Configuration Preferences',['../c_mrcRadioConfigurationPreferences.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20power_20management',['Sample code for Radio Power Management',['../c_mrcRadioPower.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20access_20technology',['Sample code for Radio Access Technology',['../c_mrcRAT.html',1,'c_mrc']]],
  ['safe_20references_20api',['Safe References API',['../c_safeRef.html',1,'c_APIs']]],
  ['secure_20storage',['Secure Storage',['../c_secStore.html',1,'legatoServicesSecStoreMain']]],
  ['secure_20storage_20admin',['Secure Storage Admin',['../c_secStoreAdmin.html',1,'legatoServicesSecStoreMain']]],
  ['semaphore_20api',['Semaphore API',['../c_semaphore.html',1,'c_APIs']]],
  ['signals_20api',['Signals API',['../c_signals.html',1,'c_APIs']]],
  ['sim',['SIM',['../c_sim.html',1,'legatoServicesModem']]],
  ['sample_20code_20for_20sim_20authentication',['Sample code for SIM Authentication',['../c_simTestAuthentication.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20identification',['Sample code for SIM Identification',['../c_simTestIdentification.html',1,'c_sim']]],
  ['sample_20code_20for_20local_20sim_20profile_20switch',['Sample code for Local SIM profile switch',['../c_simTestProfileSwitch.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20select',['Sample code for SIM Select',['../c_simTestSelect.html',1,'c_sim']]],
  ['sample_20code_20for_20local_20sim_20toolkit',['Sample code for Local SIM Toolkit',['../c_simTestSimToolkit.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20states',['Sample code for SIM States',['../c_simTestStates.html',1,'c_sim']]],
  ['singly_20linked_20list_20api',['Singly Linked List API',['../c_singlyLinkedList.html',1,'c_APIs']]],
  ['sms',['SMS',['../c_sms.html',1,'legatoServicesSMS']]],
  ['sample_20code_20for_20sms_20cell_20broadcast_20reception',['Sample code for SMS Cell Broadcast reception',['../c_smsCbSample.html',1,'']]],
  ['sms_20inbox_20service',['SMS Inbox Service',['../c_smsInbox.html',1,'legatoServicesSMS']]],
  ['sample_20code_20for_20mobile_20originated_20sms_20message',['Sample code for Mobile Originated SMS message',['../c_smsSampleMO.html',1,'c_sms']]],
  ['sample_20code_20for_20mobile_20terminated_20sms_20message',['Sample code for Mobile Terminated SMS message',['../c_smsSampleMT.html',1,'c_sms']]],
  ['supervisor_20control_20api',['Supervisor Control API',['../c_sup_ctrl.html',1,'legatoServicesSupervisorMonitoring']]],
  ['supervisor_20watchdog_20api',['Supervisor Watchdog API',['../c_sup_wdog.html',1,'']]],
  ['software_20update',['Software Update',['../c_update.html',1,'legatoServicesUpdateMain']]],
  ['system_20definition_20_2esdef',['System Definition .sdef',['../defFilesSdef.html',1,'defFiles']]],
  ['software_20package_20manager',['Software Package Manager',['../getstartedDSspm.html',1,'']]],
  ['setup_20dev_20host_20pc',['Setup Dev Host PC',['../getstartedSetupHost.html',1,'getstartedMain']]],
  ['setup_20target_20device',['Setup Target Device',['../getstartedTargetMain.html',1,'getstartedMain']]],
  ['setup_20target_20software',['Setup Target Software',['../getstartedTargetSW.html',1,'getstartedCLinstallMain']]],
  ['set_20user_20timebase',['Set User Timebase',['../howToSetUserTimebase.html',1,'howToMain']]],
  ['services_20apis',['Services APIs',['../legatoServices.html',1,'apiGuidesMain']]],
  ['secure_20storage',['Secure Storage',['../legatoServicesSecStoreMain.html',1,'legatoServices']]],
  ['sms_20messaging',['SMS Messaging',['../legatoServicesSMS.html',1,'legatoServices']]],
  ['supervisor',['Supervisor',['../legatoServicesSupervisor.html',1,'legatoServices']]],
  ['supervisor_20monitoring',['Supervisor Monitoring',['../legatoServicesSupervisorMonitoring.html',1,'legatoServicesSupervisor']]],
  ['secure_20storage',['Secure Storage',['../platformConstraintsSecStorage.html',1,'platformConstraints']]],
  ['sample_20apps',['Sample Apps',['../sampleApps.html',1,'getstartedMain']]],
  ['shell_20piping',['Shell Piping',['../sampleApps_shellPiping.html',1,'sampleApps']]],
  ['sms',['SMS',['../sampleApps_sms.html',1,'sampleApps']]],
  ['sec',['sec',['../structle__clk___time__t.html#ae28e527dbd551b3537edc1737611782f',1,'le_clk_Time_t']]],
  ['secstoreadmin_5fconnectservice',['secStoreAdmin_ConnectService',['../sec_store_admin__interface_8h.html#ad9231c3f63c28740ce137937575512f7',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fcreateiter',['secStoreAdmin_CreateIter',['../sec_store_admin__interface_8h.html#af9ad6040381e49255b70c344984f065f',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdelete',['secStoreAdmin_Delete',['../sec_store_admin__interface_8h.html#a7099f4b5e2a7b03dee054e73f9ec1c1b',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdeleteiter',['secStoreAdmin_DeleteIter',['../sec_store_admin__interface_8h.html#a1b2bfa514f93235bf5fffd3e098abf4a',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdisconnectservice',['secStoreAdmin_DisconnectService',['../sec_store_admin__interface_8h.html#ab3077b62ed029fa6d6d286c1b2e1c9bd',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgetentry',['secStoreAdmin_GetEntry',['../sec_store_admin__interface_8h.html#a69e0766bf0200b449f443a348c04bdac',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgetsize',['secStoreAdmin_GetSize',['../sec_store_admin__interface_8h.html#a4a7a4ddc84fe087a1dc6e22ec9d6fa28',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgettotalspace',['secStoreAdmin_GetTotalSpace',['../sec_store_admin__interface_8h.html#ac8eb38a1cdd75ff734a222bb129456f9',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5finterface_2eh',['secStoreAdmin_interface.h',['../sec_store_admin__interface_8h.html',1,'']]],
  ['secstoreadmin_5fiterref_5ft',['secStoreAdmin_IterRef_t',['../sec_store_admin__interface_8h.html#abdd281dcdd0bd6a42ccf4ab6581ad6e9',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fmax_5fpath_5fsize',['SECSTOREADMIN_MAX_PATH_SIZE',['../sec_store_admin__interface_8h.html#a659f4fc5eeb34940d06443436bf55d50',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fnext',['secStoreAdmin_Next',['../sec_store_admin__interface_8h.html#afb7ecb1215f1fde24ed693ef10069052',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fread',['secStoreAdmin_Read',['../sec_store_admin__interface_8h.html#a99df42615c4ab6c8ec1eb0f2f69176ea',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fwrite',['secStoreAdmin_Write',['../sec_store_admin__interface_8h.html#a6799053e02e9e9e9a84d286d1bebfedc',1,'secStoreAdmin_interface.h']]],
  ['stringize',['STRINGIZE',['../le__basics_8h.html#a3428692efe6051ef30016ffde1a9f7bb',1,'le_basics.h']]],
  ['stringize_5fexpand',['STRINGIZE_EXPAND',['../le__basics_8h.html#a7544491e9ca8040ce26fbba71ab764fb',1,'le_basics.h']]],
  ['security_2dpack',['security-pack',['../toolsHost_security-pack.html',1,'toolsHost']]],
  ['setname',['setname',['../toolsHost_setname.html',1,'toolsHost']]],
  ['settime',['settime',['../toolsHost_settime.html',1,'toolsHost']]],
  ['settz',['settz',['../toolsHost_settz.html',1,'toolsHost']]],
  ['simu',['simu',['../toolsHost_simu.html',1,'toolsHost']]],
  ['startapp',['startapp',['../toolsHost_startapp.html',1,'toolsHost']]],
  ['startlegato',['startlegato',['../toolsHost_startlegato.html',1,'toolsHost']]],
  ['statapp',['statapp',['../toolsHost_statapp.html',1,'toolsHost']]],
  ['stopapp',['stopapp',['../toolsHost_stopapp.html',1,'toolsHost']]],
  ['stoplegato',['stoplegato',['../toolsHost_stoplegato.html',1,'toolsHost']]],
  ['sdir',['sdir',['../toolsTarget_sdir.html',1,'toolsTarget']]],
  ['setnet',['setNet',['../toolsTarget_setNet.html',1,'toolsTarget']]]
];
