var tools_host =
[
    [ "gettargettype", "tools_host_gettargettype.html", null ],
    [ "startlegato", "tools_host_startlegato.html", null ],
    [ "startapp", "tools_host_startapp.html", null ],
    [ "stoplegato", "tools_host_stoplegato.html", null ],
    [ "releaselegato", "tools_host_releaselegato.html", null ],
    [ "statapp", "tools_host_statapp.html", null ],
    [ "instlegato", "tools_host_instlegato.html", null ],
    [ "setname", "tools_host_setname.html", null ],
    [ "simu", "tools_host_simu.html", null ],
    [ "security-pack", "tools_host_security-pack.html", null ],
    [ "av-pack", "tools_host_av-pack.html", null ],
    [ "fwupdate", "tools_host_fwupdate.html", null ],
    [ "instsys", "tools_host_instsys.html", null ],
    [ "lsapp", "tools_host_lsapp.html", null ],
    [ "legato-qemu", "tools_host_legato-qemu.html", null ],
    [ "mklegatoimg", "tools_host_mklegatoimg.html", null ],
    [ "stopapp", "tools_host_stopapp.html", null ],
    [ "settz", "tools_host_settz.html", null ],
    [ "createsdk", "tools_host_createsdk.html", null ],
    [ "configtargetssh", "tools_host_configtargetssh.html", null ],
    [ "rmapp", "tools_host_rmapp.html", null ],
    [ "instapp", "tools_host_instapp.html", null ],
    [ "settime", "tools_host_settime.html", null ]
];