var searchData=
[
  ['search',['Search',['../about_docs_search.html',1,'aboutMain']]],
  ['security',['Security',['../basic_security.html',1,'basicConcepts']]],
  ['sandboxes',['Sandboxes',['../basic_security_sandbox.html',1,'basicSecurity']]],
  ['smack',['SMACK',['../basic_security_smack.html',1,'basicSecurity']]],
  ['system_20clock_20api',['System Clock API',['../c_clock.html',1,'c_APIs']]],
  ['safe_20references_20api',['Safe References API',['../c_safe_ref.html',1,'c_APIs']]],
  ['secure_20storage',['Secure Storage',['../c_sec_store.html',1,'legatoServices']]],
  ['semaphore_20api',['Semaphore API',['../c_semaphore.html',1,'c_APIs']]],
  ['signals_20api',['Signals API',['../c_signals.html',1,'c_APIs']]],
  ['sim',['SIM',['../c_sim.html',1,'legatoServices']]],
  ['singly_20linked_20list_20api',['Singly Linked List API',['../c_singly_linked_list.html',1,'c_APIs']]],
  ['sms',['SMS',['../c_sms.html',1,'legatoServices']]],
  ['sms_20inbox_20service',['SMS Inbox Service',['../c_sms_inbox.html',1,'legatoServices']]],
  ['sample_20code_20for_20mobile_20originated_20sms_20message',['Sample code for Mobile Originated SMS message',['../c_sms_sample_m_o.html',1,'c_sms']]],
  ['sample_20code_20for_20mobile_20terminated_20sms_20message',['Sample code for Mobile Terminated SMS message',['../c_sms_sample_m_t.html',1,'c_sms']]],
  ['supervisor_20control_20api',['Supervisor Control API',['../c_sup_ctrl.html',1,'legatoServicesSupervisor']]],
  ['supervisor_20watchdog_20api',['Supervisor Watchdog API',['../c_sup_wdog.html',1,'']]],
  ['software_20update',['Software Update',['../c_update.html',1,'legatoServices']]],
  ['system_20definition_20_2esdef',['System Definition .sdef',['../def_files_sdef.html',1,'defFiles']]],
  ['software_20package_20manager',['Software Package Manager',['../getstarted_d_sspm.html',1,'getstartedDSlinux']]],
  ['setup_20dev_20host_20pc',['Setup Dev Host PC',['../getstarted_setup_host.html',1,'getstartedMain']]],
  ['setup_20target_20device',['Setup Target Device',['../getstarted_setup_target.html',1,'getstartedMain']]],
  ['setup_20target_20software',['Setup Target Software',['../getstarted_target_s_w.html',1,'getstartedCLinstallMain']]],
  ['services_20apis',['Services APIs',['../legato_services.html',1,'index']]],
  ['supervisor',['Supervisor',['../legato_services_supervisor.html',1,'legatoServices']]],
  ['sample_20apps',['Sample Apps',['../sample_apps.html',1,'basicMain']]],
  ['sms',['SMS',['../sample_apps_sms.html',1,'sampleApps']]],
  ['security_2dpack',['security-pack',['../tools_host_security-pack.html',1,'toolsHost']]],
  ['setname',['setname',['../tools_host_setname.html',1,'toolsHost']]],
  ['settime',['settime',['../tools_host_settime.html',1,'toolsHost']]],
  ['settz',['settz',['../tools_host_settz.html',1,'toolsHost']]],
  ['simu',['simu',['../tools_host_simu.html',1,'toolsHost']]],
  ['startapp',['startapp',['../tools_host_startapp.html',1,'toolsHost']]],
  ['startlegato',['startlegato',['../tools_host_startlegato.html',1,'toolsHost']]],
  ['statapp',['statapp',['../tools_host_statapp.html',1,'toolsHost']]],
  ['stopapp',['stopapp',['../tools_host_stopapp.html',1,'toolsHost']]],
  ['stoplegato',['stoplegato',['../tools_host_stoplegato.html',1,'toolsHost']]],
  ['sdir',['sdir',['../tools_target_sdir.html',1,'toolsTarget']]],
  ['setnet',['setNet',['../tools_target_set_net.html',1,'toolsTarget']]]
];
